apiVersion: v1
kind: Template
metadata:
  name: template-subscriber-information
  annotations:
    description: "Template para generacion del servicio subscriber information de Telefonica"
    tags: "subscriber-information,fuse"
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      labels:
        app: subscriber-information
      name: configmap-subscriber-information
      namespace: mi-movistar
    data:
      spring.application.name: subscriber-information
      server.port: "8080"
      server.session.timeout: "90000"
      server.connection-timeout: "90000"
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: subscriber-information
      name: subscriber-information
    spec:
      replicas: 1
      selector:
        app: subscriber-information
        deploymentconfig: subscriber-information
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "true"
          labels:
            app: subscriber-information
            deploymentconfig: subscriber-information
        spec:
          containers:
            - name: subscriber-information
              image: image-registry.openshift-image-registry.svc:5000/mi-movistar/subscriber-information:latest
              env:
                - name: SPRING_APPLICATION_JSON
                  value: '{"server":{"undertow":{"io-threads":10, "worker-threads":80 }}}'
                - name: JAVA_OPTIONS
                  value: '-Xms640m -Xmx1024m -Dfile.encoding=ISO-8859-1'
              envFrom:
                - configMapRef:
                    name: configmap-subscriber-information
              resources:
                limits:
                  cpu: 800m
                  memory: 300Mi
                requests:
                  cpu: 800m
                  memory: 300Mi
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: subscriber-information
        app.kubernetes.io/component: subscriber-information
        app.kubernetes.io/instance: subscriber-information
      name: subscriber-information
      namespace: mi-movistar
    spec:
      ports:
        - name: http-web
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: subscriber-information
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      labels:
        app: subscriber-information
      name: hpa-subscriber-information
      namespace: mi-movistar
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: subscriber-information
      minReplicas: 3
      maxReplicas: 5
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              averageUtilization: 80
              type: Utilization
  - apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: subscriber-information-mtls
    spec:
      host: subscriber-information
      trafficPolicy:
        tls:
          mode: ISTIO_MUTUAL